### ISSUE TITLE
Query parameter issues

### ISSUE THREAD

**Issue by johnnycupcakes** [HelloFax/hellosign-nodejs-sdk#8] opened 2016-02-04 19:17 UTC
I'm having a difficult time with a date query for completed docs.

I'm using the node hellosign-sdk (1.1.8 running on node v4.2.1)

If I run a query like this:

'complete:true'

I get 34 results. That's how many completed signed docs I have. OK, no problem.

If I set a query to:

'created:{2014-01-01 TO 2016-12-31}'

I get 68 results. (That time span covers all my docs, so you can see that roughly 1/2 have been completed.)

But if I change that query to:

'completed:{2014-01-01 TO 2016-12-31}'

I get zero results. I'm not sure I understand that at all.

In fact, I don't think I've gotten a query with "completed" in it to return any results. It doesn't appear to work at all. The docs say this about "completed":

completed The date (and optional time) of the final signature SignatureRequest only Date

From this I would gather that I should be a able to query on completion date/time.

Well, let me suggest that the documentation around queries can be improved quite a bit.
For example, I just figured out that the '+' signs needed by the query string to separate 'TO' and 'AND', etc are inserted by the SDK and should be spaces instead. How could I work that out except through experimentation. There are ZERO complete examples of a query with date ranges.

Best, 
Dave J

**Comment by renderf0x** [comment] 2016-02-04 21:08
OK, so it looks like there's a couple things going on here:

1) The [documentation for search](https://www.hellosign.com/api/reference#Search) needs to be updated to include code examples for each SDK, not just for cURL, as does currently.
Great suggestion.

2) As far as I can see, we don't actually index the completed date as a parameter for these.
I tried on the site UI at hellosign.com, and was able to confirm, as I could search for `created:{2015-05-01 TO 2015-12-01}` but not `completed:{2015-05-01 TO 2015-12-01}`.

I'm going to open an internal ticket to look into this. We either need to start doing this search (as the docs say we do), or edit the docs to remove this.

**Comment by djacobow** [comment] 2016-02-04 21:57
I'm the original source of this report. I'm pleased to see that I'm not completely crazy. I didn't think this was an SDK issue, because the SDK code for assembly the options is generic. So, if I understand correctly, this feature is in the docs but is not implemented.

Well, let me be the first to make this feature request!  :-)

It would really help our application (and your service) by greatly diminishing the number of requests we need to check on. We are trying to use your callback system to get updates on requests, but we will also infrequently poll to catch anything that might slip through the cracks and also for dashboard purposes.

**Comment by renderf0x** [comment] 2016-02-04 22:01
Hey there @djacobow.

Thanks muchly for surfacing that -- as above, I've confirmed this isn't currently working, and I have a ticket open for it and it's on the stack to look into.

Agreed - since we're advertising this, we should support it if we can.
Failing that, the docs should at least match what we have working and implemented.

We'll update this GitHub issue when we have a fix for this.

Thanks again!

**Comment by rmelencio** [comment] 2016-03-14 18:12
Hey @johnnycupcakes 

To get all completed documents, please continue to use ‘complete:true’.

We don’t yet support getting a list of completed documents by date range, but this is on our road map.  We’ve updated our documentation to reflect this.

-Ronald

**Comment by latoyazamill** [comment] 2020-04-13 21:32
**Closing the loop here:** This was reported as a feature enhancement. For more information on when this may be released, please subscribe to our product updates here: [Product Release Notes](https://faq.hellosign.com/hc/en-us/categories/202937107-Product-Release-Notes)

_(Internal Note: HSAPI-I-184)_

**Closed as completed by latoyazamill** 2020-04-13 21:32 UTC

**Comment by latoyazamill** [comment] 2020-04-13 21:35
For future reference, please refer to our search guide for our latest options to query :) Found here: [Search](https://app.hellosign.com/api/reference#Search) Thanks!
