### ISSUE TITLE
Canceling Signature Request hangs

### ISSUE THREAD

**Issue by MikeyF-Anovia** [HelloFax/hellosign-nodejs-sdk#21] opened 2016-10-28 21:58 UTC
Hi. I sent this to support@hellosign. Nic said post the issue here so I could get notifications when it was fixed, etc, and what not. 

It would appear that the node SDK function hellosign.signatureRequest.cancel(signatureRequestId) never fires/calls the .then() or .catch() promise callbacks

I attempted one just now in debug mode and my breakpoints on either were never encountered.
When I look in the dashboard the signature request still shows "out for signature" but when when I click on it I get the error: The content you requested was not found, or you do not have permission to access it.

If I do a Postman post to https://api.hellosign.com/v3/signature_request/cancel/{signatureid}
I get back no response body but the http code is 200.

In either case, the signature request does seem to get canceled and is no longer accessible to click on from the dashboard nor from the email notification the user received. However the dashboard still shows that it is "out for signature"

So, my current issues are,
1) The HelloSign Node SDK (1.1.12) never calls/returns on the .then or .catch promise methods when canceling signature requests.
2) The dashboard shows a status of "out for signature" rather than canceled.

Thanks.

**Comment by npbee** [comment] 2017-07-12 23:52
@MikeyF-Anovia, thanks for this thorough report!  I realize the issue is quite old at this point, but I just wanted to follow up with some updates:

Regarding the first issue, you're right this is a bug in the SDK.  I've made an internal request to prioritize a fix for this and I'll make sure to update here when that happens.

Regarding the second issue, I believe this may have been the result of a slow re-indexing after the request was cancel.  It's possible that the search index was not quite up to date when viewing from the dashboard, so even though it still said "out for signature" the request was technically already deleted and trying to access it resulted in the error message you saw.  

Thanks!

**Comment by MikeyF-Anovia** [comment] 2017-07-13 14:02
Thank you! I am glad I could be of help.

**Comment by alexmac05** [comment] 2017-10-15 03:18
@MikeyF-Anovia @npbee 
I also realize the issue is still quite old. I was assigned to looking into this after more reports were made and what I have found is that this is by design. I first looked in the sdk but I could not find the error and then I tested it with python and curl and basically you just get a 200 response but no response object. 

Reading here:

https://app.hellosign.com/api/reference#cancel_incomplete_signature_request
It states:
Cancelation is asynchronous and a successful call to this endpoint will return an empty 200 OK response if the signature request is eligible to be canceled and has been successfully queued. 

For node this means that the local callback function never fires which is confusing. 

I've now made an internal request at HelloSign to have this better documented and the sample code for node changed to illustrate this for the cancel.

**Closed as completed by alexmac05** 2017-10-15 03:18 UTC

**Comment by MikeyF-Anovia** [comment] 2017-10-16 13:52
Aaaah...that makes sense. I'll adjust my code.Thanks!

**Comment by bigicoin** [comment] 2018-12-11 19:40
If the local callback function never fires, how can our application code determine success vs failure from this call? Note that failures do indeed get into the `.catch()` case.

So imagine the code:
`const result = await hellosign.signatureRequest.cancel('...').then(res => { ... }).catch(err => { ... });`

Possible outcomes:
1. Success case, this await hangs forever.
2. Failure case, it gets into `.catch()` and that runs.

Possible scenarios:
1. Do not use await to wait for this async function, in which case we don't know if `.catch()` ever fired before the HTTP request handler ends.
2. Do use await, but the HTTP request hangs forever.

There's no good way to handle both cases then?
